### ISSUE TITLE
MemoriseProject primary key

### ISSUE THREAD

**Issue by Iheve** [tonyguolei/projet_dac#10]
I think that we should change the table MemoriseProject to suppress the "idMemoriseProject" column.
Indeed, using idProject,idUser as primary key would be much more convenient : it forbids to memorise two times the same project, and it makes removal easy.

**Comment by Jojolejobar** [comment]
I already explain why I hasn't done this way at the first time. It's because of ejb: when you have a primary key with two column or more, the result, in java, is two classes one for the table and one just for the key. So when you want to initialise the table you have to create to objects, that's why I had these "virtual keys".
If it's really bothered you I can change it.

**Comment by Iheve** [comment]
I think that for this usage, it would be a good thing to change it. Thank
you :-)
Le 4 janv. 2015 00:51, "Guillaume Perrin" <notifications@github.com> a
écrit :

**Comment by Jojolejobar** [comment]
We can't generate EJB for table which only contains a primary key. Also, we can add a unique constraint on the two columns to solve your problem

**Comment by Iheve** [comment]
OK, go for that :-)
Le 4 janv. 2015 13:39, "Guillaume Perrin" <notifications@github.com> a
écrit :
