### ISSUE TITLE
Project not updated at creation

### ISSUE THREAD

**Issue by Iheve** [tonyguolei/projet_dac#9]
When a project is just created, I think glassfish keep in memory the creation value. It does not get it from the database. therefore, the date format for the deadline is different, and the creation date is unavailable.

Is it possible to force glassfish to refresh the EJB entity after the "persist" operation ?

**Comment by tonyguolei** [comment]
I have no idea what should I do. Could you please specify where is the
problem. It's better that If you can tell me how to reproduce the problem.
For me, entitybean interact with database, there is no much relation with
jee server. And I have not seen such problem during development.

Lei
Le 4 janv. 2015 00:07, "Thibaut Coutelou" <notifications@github.com> a
écrit :

**Comment by Iheve** [comment]
How to reproduce the problem:
* Login
* Create a new project
* List project
* Click on the project just created

Clues that comething went wrong:
* There is a blank instead of the creation date
* The format of the deadline is not the same as other dates
* The format of the goal does not have two decimals

**Comment by tonyguolei** [comment]
Hi, Thibault,

I have tried 2 versions of our application.

The 1st version is the code after my commit for "fixer the date of creation
du project". Everything is ok. There is no problem when I click on the
project just created. I have add a copy screen in attached document.

The 2nd version is the last version of our application after your commit.
There is the problem as you pointed out.

So, I think the problem comes from your side for JSP code, instead of
problem of ejb or glassfish. There is no reason that ejb and glassfish
worked before in 1st version, but not the 2nd version. In this case, I
think you should check your modification with the code that you have pushed
after the 1st version. If you want, I can send your the code of 1st version.

Lei

2015-01-04 14:57 GMT+01:00 Thibaut Coutelou <notifications@github.com>:

**Comment by Iheve** [comment]
Hi,

I did a git co d5cda59 (fixer the date of creation du project).
I do have the problem even with that version.
Maybe we can have a look to this tomorow.

By the way, I was not able to see your screen copy : github does not forward attachment.

Thibaut

**Comment by tonyguolei** [comment]
I didn't know guthub doesn't allow attached document. It's my bad :)
In addition, I succeed to reproduce the problem. I should logout and clear
the cache to reproduce it. If not, this bug will be covered. I have tested
even the version before my commit, it still has this problem. So I think
maybe you are right, glassfish does not read value from database(I am not
sur if glassfish memorise the value).
I will try to understand why.

Lei
Le 4 janv. 2015 18:05, "Thibaut Coutelou" <notifications@github.com> a
écrit :
